{% set name = "curtsies" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/curtsies-{{ version }}.tar.gz
  sha256: 62d10f349c553845306556a7f2663ce96b098d8c5bbc40daec7a6eedde1622b0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - blessed >=1.5
    - cwcwidth

test:
  imports:
    - curtsies
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/bpython/curtsies
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Curses-like terminal wrapper, with colored strings!

extra:
  recipe-maintainers:
    - scopatz
    - mariusvniekerk
