{% set name = "curtsies" %}
{% set version = "0.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/curtsies-{{ version }}.tar.gz
  sha256: 102a0ffbf952124f1be222fd6989da4ec7cce04e49f613009e5f54ad37618825

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=43
  run:
    - python >={{ python_min }}
    - blessed >=1.5
    - cwcwidth

test:
  imports:
    - curtsies
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/bpython/curtsies
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Curses-like terminal wrapper, with colored strings!

extra:
  recipe-maintainers:
    - scopatz
    - mariusvniekerk
