{% set name = "curtsies" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/curtsies-{{ version }}.tar.gz
  sha256: 6ebe33215bd7c92851a506049c720cca4cf5c192c1665c1d7a98a04c4702760e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - blessed >=1.5
    - cwcwidth

test:
  imports:
    - curtsies
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bpython/curtsies
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Curses-like terminal wrapper, with colored strings!

extra:
  recipe-maintainers:
    - scopatz
    - mariusvniekerk
